package allocation

import allocation.*
import allocation.facts.*
import allocation.actions.*
import allocation.newagents.*
import uk.ac.imperial.presage2.core.IntegerTime
import java.lang.Math

global org.apache.log4j.Logger logger

declare Processed
	action : TimestampedAction
end

declare Appropriated
	agent : String
	round : int
	quantity : double
end

rule "Max level" // Given an overfilled CommonPool, reset resource level to maximum
	salience -11
	ruleflow-group 'init'
	when
		$pool : CommonPool( resourceLevel > maxLevel, $max : maxLevel)
	then
		modify($pool) {
			setResourceLevel($max);
		}
		logger.info("Pool was overfilled, reseting to max level");
end

rule "Refill pool"
	salience -10
	ruleflow-group 'init'
	when
		// when a new round occurs
		$t : IntegerTime() 
		// and there is a pool which has not been filled in this round
		$pool : CommonPool( $t.intValue() > getLastFilled())
		// and the institution governing this pool is in the 'Exclude' phase
		Institution( pools contains $pool )
	then // refill pool
		double fillAmount = $pool.getMaxLevel() / 2;
		int time = $t.intValue();
		if(time < 50) {
			fillAmount *= 1;
		} else if(time < 100) {
			fillAmount *= 0.95;
		} else if(time < 150) {
			fillAmount *= 0.87;
		} else if(time < 200) {
			fillAmount *= 0.52;
		} else if(time < 250) {
			fillAmount *= 0.92;
		} else if(time < 300) {
			fillAmount *= 0.97;
		} else if(time < 350) {
			fillAmount *= 0.62;
		} else if(time < 400) {
			fillAmount *= 0.90;
		} else if(time < 450) {
			fillAmount *= 0.50;
		} else {
			fillAmount *= 0.91;
		}
		modify($pool) {
			setResourceLevel( $pool.getResourceLevel() + fillAmount),
			setLastFilled( time )
		}
		logger.info("Fill resource by "+ fillAmount +", pool resource level is "+ $pool.getResourceLevel() );
end

rule "NonMember appropriation"
	salience 1000
	ruleflow-group "appropriate"
	no-loop
	when
		$t : IntegerTime( )
		$nonmember : NonMember( $pid : pool )
		$pool : CommonPool( id == $pid )
		not Appropriated( round == $t.intValue(), agent == $nonmember.getName() )
	then
		Appropriated app = new Appropriated( $nonmember.getName(), $t.intValue(), $nonmember.appropriate( $pool ) );
		insert( app );
		modify($pool) {
			setResourceLevel( $pool.getResourceLevel() - app.getQuantity() )
		}
		logger.info(app);
		logger.info($pool);
end

rule "End of the world"
	ruleflow-group 'init'
	when
		$pool : CommonPool( resourceLevel < 0 )
	then
		retract($pool);
		logger.info("DEPLEATED!!");
end

rule "Prune Appropriate"
	when
		$pool : CommonPool( $id : id )
		Institution( pools contains $pool, $round : round )
		$a : Appropriate( pool == $id, round < $round )
	then
		retract($a);
		//logger.info("Prune "+ $a);
end

rule "Prune Processed"
	when
		$p : Processed($a : action)
		not(exists(TimestampedAction(this == $p.action)))
	then
		retract( $p );
end

